DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'app') THEN
        CREATE SCHEMA app;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS app."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'app') THEN
            CREATE SCHEMA app;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE TABLE app."AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE TABLE app."AspNetUsers" (
        "Id" text NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE TABLE app."FlightStock" (
        "FlightStockId" integer GENERATED BY DEFAULT AS IDENTITY,
        "DomainEntityId" integer NOT NULL,
        "Title" character varying(200) NOT NULL,
        "UnitPrice" numeric(12,2) NOT NULL,
        "Stock" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_FlightStock" PRIMARY KEY ("FlightStockId"),
        CONSTRAINT "CK_FlightStock_Stock" CHECK ("Stock" >= 0),
        CONSTRAINT "CK_FlightStock_UnitPrice" CHECK ("UnitPrice" >= 0)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE TABLE app."PurchaseOrder" (
        "PurchaseOrderId" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" character varying(450) NOT NULL,
        "UserEmailSnapshot" character varying(320) NOT NULL,
        "Total" numeric(12,2) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_PurchaseOrder" PRIMARY KEY ("PurchaseOrderId"),
        CONSTRAINT "CK_PurchaseOrder_Total" CHECK ("Total" >= 0)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE TABLE app."AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES app."AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE TABLE app."AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES app."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE TABLE app."AspNetUserLogins" (
        "LoginProvider" character varying(128) NOT NULL,
        "ProviderKey" character varying(128) NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES app."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE TABLE app."AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES app."AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES app."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE TABLE app."AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" character varying(128) NOT NULL,
        "Name" character varying(128) NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES app."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE TABLE app."ShoppingCartItem" (
        "ShoppingCartItemId" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" character varying(450) NOT NULL,
        "FlightStockId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "AddedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_ShoppingCartItem" PRIMARY KEY ("ShoppingCartItemId"),
        CONSTRAINT "CK_ShoppingCartItem_Quantity" CHECK ("Quantity" > 0),
        CONSTRAINT "FK_ShoppingCartItem_FlightStock_FlightStockId" FOREIGN KEY ("FlightStockId") REFERENCES app."FlightStock" ("FlightStockId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE TABLE app."PaymentTransaction" (
        "PaymentTransactionId" integer GENERATED BY DEFAULT AS IDENTITY,
        "PurchaseOrderId" integer NOT NULL,
        "Provider" character varying(30) NOT NULL,
        "ClientTransactionId" character varying(100) NOT NULL,
        "PayphonePaymentUrl" character varying(2048),
        "PayphoneTransactionId" character varying(150),
        "PayPalOrderId" character varying(150),
        "PayPalCaptureId" character varying(150),
        "PayPalApprovalUrl" character varying(2048),
        "GatewayResponseSanitized" character varying(4000),
        "AmountInCents" integer NOT NULL,
        "Status" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "ConfirmedAt" timestamp with time zone,
        CONSTRAINT "PK_PaymentTransaction" PRIMARY KEY ("PaymentTransactionId"),
        CONSTRAINT "CK_PaymentTransaction_Amount" CHECK ("AmountInCents" >= 0),
        CONSTRAINT "FK_PaymentTransaction_PurchaseOrder_PurchaseOrderId" FOREIGN KEY ("PurchaseOrderId") REFERENCES app."PurchaseOrder" ("PurchaseOrderId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE TABLE app."PurchaseOrderDetail" (
        "PurchaseOrderDetailId" integer GENERATED BY DEFAULT AS IDENTITY,
        "PurchaseOrderId" integer NOT NULL,
        "FlightStockId" integer NOT NULL,
        "ItemTitleSnapshot" character varying(200) NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric(12,2) NOT NULL,
        "Subtotal" numeric(12,2) NOT NULL,
        CONSTRAINT "PK_PurchaseOrderDetail" PRIMARY KEY ("PurchaseOrderDetailId"),
        CONSTRAINT "CK_PurchaseOrderDetail_Quantity" CHECK ("Quantity" > 0),
        CONSTRAINT "CK_PurchaseOrderDetail_Subtotal" CHECK ("Subtotal" >= 0),
        CONSTRAINT "CK_PurchaseOrderDetail_UnitPrice" CHECK ("UnitPrice" >= 0),
        CONSTRAINT "FK_PurchaseOrderDetail_FlightStock_FlightStockId" FOREIGN KEY ("FlightStockId") REFERENCES app."FlightStock" ("FlightStockId") ON DELETE RESTRICT,
        CONSTRAINT "FK_PurchaseOrderDetail_PurchaseOrder_PurchaseOrderId" FOREIGN KEY ("PurchaseOrderId") REFERENCES app."PurchaseOrder" ("PurchaseOrderId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON app."AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON app."AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON app."AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON app."AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON app."AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE INDEX "EmailIndex" ON app."AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON app."AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE UNIQUE INDEX "IX_FlightStock_DomainEntityId" ON app."FlightStock" ("DomainEntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE UNIQUE INDEX "IX_PaymentTransaction_ClientTransactionId" ON app."PaymentTransaction" ("ClientTransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE UNIQUE INDEX "IX_PaymentTransaction_PayPalCaptureId" ON app."PaymentTransaction" ("PayPalCaptureId") WHERE "PayPalCaptureId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE UNIQUE INDEX "IX_PaymentTransaction_PayPalOrderId" ON app."PaymentTransaction" ("PayPalOrderId") WHERE "PayPalOrderId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE UNIQUE INDEX "IX_PaymentTransaction_PayphoneTransactionId" ON app."PaymentTransaction" ("PayphoneTransactionId") WHERE "PayphoneTransactionId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE INDEX "IX_PaymentTransaction_PurchaseOrderId" ON app."PaymentTransaction" ("PurchaseOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE INDEX "IX_PurchaseOrder_UserId_CreatedAt" ON app."PurchaseOrder" ("UserId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE INDEX "IX_PurchaseOrderDetail_FlightStockId" ON app."PurchaseOrderDetail" ("FlightStockId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE INDEX "IX_PurchaseOrderDetail_PurchaseOrderId" ON app."PurchaseOrderDetail" ("PurchaseOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE INDEX "IX_ShoppingCartItem_FlightStockId" ON app."ShoppingCartItem" ("FlightStockId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    CREATE UNIQUE INDEX "IX_ShoppingCartItem_UserId_FlightStockId" ON app."ShoppingCartItem" ("UserId", "FlightStockId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM app."__EFMigrationsHistory" WHERE "MigrationId" = '20260729204920_InitialApplicationSchema') THEN
    INSERT INTO app."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260729204920_InitialApplicationSchema', '10.0.4');
    END IF;
END $EF$;
COMMIT;

