\set ON_ERROR_STOP on

CREATE SCHEMA airportdb;

COMMENT ON SCHEMA airportdb IS
  'AirportDB migrada desde el volcado MySQL Shell 8.0.25. Datos originales bajo licencia CC BY 4.0.';

CREATE TABLE airportdb.airport (
  airport_id smallint GENERATED BY DEFAULT AS IDENTITY,
  iata character(3),
  icao character(4) NOT NULL,
  name varchar(50) NOT NULL
);

CREATE TABLE airportdb.airport_geo (
  airport_id smallint NOT NULL,
  name varchar(50) NOT NULL,
  city varchar(50),
  country varchar(50),
  latitude numeric(11,8) NOT NULL,
  longitude numeric(11,8) NOT NULL,
  geolocation bytea NOT NULL,
  location point GENERATED ALWAYS AS (
    point(longitude::double precision, latitude::double precision)
  ) STORED
);

COMMENT ON COLUMN airportdb.airport_geo.geolocation IS
  'Binario espacial WKB de MySQL, decodificado de Base64 sin alterar sus bytes (incluye el prefijo SRID de MySQL).';

COMMENT ON COLUMN airportdb.airport_geo.location IS
  'Punto consultable de PostgreSQL derivado como (longitud, latitud).';

-- Área de paso: el volcado guarda geolocation en Base64.
CREATE UNLOGGED TABLE airportdb.airport_geo_import_stage (
  airport_id smallint NOT NULL,
  name varchar(50) NOT NULL,
  city varchar(50),
  country varchar(50),
  latitude numeric(11,8) NOT NULL,
  longitude numeric(11,8) NOT NULL,
  geolocation_base64 text NOT NULL
);

CREATE TABLE airportdb.airport_reachable (
  airport_id smallint NOT NULL,
  hops integer
);

CREATE TABLE airportdb.airline (
  airline_id smallint GENERATED BY DEFAULT AS IDENTITY,
  iata character(2) NOT NULL,
  airlinename varchar(30),
  base_airport smallint NOT NULL
);

CREATE TABLE airportdb.airplane_type (
  type_id integer GENERATED BY DEFAULT AS IDENTITY,
  identifier varchar(50),
  description text
);

CREATE TABLE airportdb.airplane (
  airplane_id integer GENERATED BY DEFAULT AS IDENTITY,
  capacity integer NOT NULL,
  type_id integer NOT NULL,
  airline_id integer NOT NULL,
  CONSTRAINT airplane_capacity_unsigned_chk
    CHECK (capacity BETWEEN 0 AND 16777215)
);

CREATE TABLE airportdb.flightschedule (
  flightno character(8) NOT NULL,
  "from" smallint NOT NULL,
  "to" smallint NOT NULL,
  departure time without time zone NOT NULL,
  arrival time without time zone NOT NULL,
  airline_id smallint NOT NULL,
  monday boolean DEFAULT false,
  tuesday boolean DEFAULT false,
  wednesday boolean DEFAULT false,
  thursday boolean DEFAULT false,
  friday boolean DEFAULT false,
  saturday boolean DEFAULT false,
  sunday boolean DEFAULT false
);

CREATE TABLE airportdb.passenger (
  passenger_id integer GENERATED BY DEFAULT AS IDENTITY,
  passportno character(9) NOT NULL,
  firstname varchar(100) NOT NULL,
  lastname varchar(100) NOT NULL
);

CREATE TABLE airportdb.passengerdetails (
  passenger_id integer NOT NULL,
  birthdate date NOT NULL,
  sex character(1),
  street varchar(100) NOT NULL,
  city varchar(100) NOT NULL,
  zip smallint NOT NULL,
  country varchar(100) NOT NULL,
  emailaddress varchar(120),
  telephoneno varchar(30)
);

CREATE TABLE airportdb.employee (
  employee_id integer GENERATED BY DEFAULT AS IDENTITY,
  firstname varchar(100) NOT NULL,
  lastname varchar(100) NOT NULL,
  birthdate date NOT NULL,
  sex character(1),
  street varchar(100) NOT NULL,
  city varchar(100) NOT NULL,
  zip smallint NOT NULL,
  country varchar(100) NOT NULL,
  emailaddress varchar(120),
  telephoneno varchar(30),
  salary numeric(8,2),
  department varchar(20),
  username varchar(20),
  password character(32),
  CONSTRAINT employee_department_chk CHECK (
    department IS NULL OR department IN (
      'Marketing',
      'Buchhaltung',
      'Management',
      'Logistik',
      'Flugfeld'
    )
  )
);

CREATE TABLE airportdb.flight (
  flight_id integer GENERATED BY DEFAULT AS IDENTITY,
  flightno character(8) NOT NULL,
  "from" smallint NOT NULL,
  "to" smallint NOT NULL,
  departure timestamp without time zone NOT NULL,
  arrival timestamp without time zone NOT NULL,
  airline_id smallint NOT NULL,
  airplane_id integer NOT NULL
);

CREATE TABLE airportdb.flight_log (
  flight_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
  log_date timestamp without time zone NOT NULL,
  "user" varchar(100) NOT NULL,
  flight_id integer NOT NULL,
  flightno_old character(8) NOT NULL,
  flightno_new character(8) NOT NULL,
  from_old smallint NOT NULL,
  to_old smallint NOT NULL,
  from_new smallint NOT NULL,
  to_new smallint NOT NULL,
  departure_old timestamp without time zone NOT NULL,
  arrival_old timestamp without time zone NOT NULL,
  departure_new timestamp without time zone NOT NULL,
  arrival_new timestamp without time zone NOT NULL,
  airplane_id_old integer NOT NULL,
  airplane_id_new integer NOT NULL,
  airline_id_old smallint NOT NULL,
  airline_id_new smallint NOT NULL,
  comment varchar(200),
  CONSTRAINT flight_log_id_unsigned_chk CHECK (flight_log_id >= 0)
);

CREATE TABLE airportdb.weatherdata (
  log_date date NOT NULL,
  "time" time without time zone NOT NULL,
  station integer NOT NULL,
  temp numeric(3,1) NOT NULL,
  humidity numeric(4,1) NOT NULL,
  airpressure numeric(10,2) NOT NULL,
  wind numeric(5,2) NOT NULL,
  weather varchar(30),
  winddirection smallint NOT NULL,
  CONSTRAINT weatherdata_weather_chk CHECK (
    weather IS NULL OR weather IN (
      'Nebel-Schneefall',
      'Schneefall',
      'Regen',
      'Regen-Schneefall',
      'Nebel-Regen',
      'Nebel-Regen-Gewitter',
      'Gewitter',
      'Nebel',
      'Regen-Gewitter'
    )
  )
);

CREATE TABLE airportdb.booking (
  booking_id integer GENERATED BY DEFAULT AS IDENTITY,
  flight_id integer NOT NULL,
  seat character(4),
  passenger_id integer NOT NULL,
  price numeric(10,2) NOT NULL
);
